### PR TITLE
[820] remove title from nav bar on mobile and change login button to link

### PR DESCRIPTION
**Pull request by cedar-technologies**
Hi,

Here's a suggestion to fix issue [EPIC#WellSummary | Mobile UI interface Webpage title |2| !](https://trello.com/c/qJy48pDX)

I also changed the login button to be a link in the mobile menu, I couldn't test the logout.

Thanks

### CODE REVIEW

**Comment by Sybrand** [comment]
@cedar-technologies thank you for the submission, I've changed the title of the PR to match our convention: "[trello ticket number] Description".

**Comment by DerekRoberts** [comment]
@cedar-technologies Every Trello ticket is numbered at the link below, but we may have neglected to document that.  You're more than welcome to revise CONTRIBUTING.md!  Also, thanks for the contributions and good to meet you, Mr. Probably Christian's Friend.  ;)

https://trello.com/b/2UQZgXHR/wells-project-board

**Comment by cedar-technologies** [comment]
Thanks @DerekRoberts I will update the Contributing.md with this information, thanks for merging my contribution ;-). I haven't meet christian, I'm working for sierra and Dan Wolfe told me about your project ;-)

**Comment by DerekRoberts** [comment]
@cedar-technologies So I was fed bad info!  Please tell Dan we said thanks.  Would you mind reopening this PR?  It was closed before we could finish testing and merging.

**Comment by cwevans** [comment]
[EPIC#WellSummary | Mobile UI interface Webpage title |2| !](https://trello.com/c/qJy48pDX/820-epicwellsummary-mobile-ui-interface-webpage-title-2)

**Pull request closed without merging**
