### PR TITLE
Fixes issues in user testing feedback on aquifer search and view 

### PR DESCRIPTION
**Pull request by rfb**

### CODE REVIEW

**Comment by rfb** [comment]
[EPIC#AquiferData | Tweaks |2| !!!](https://trello.com/c/l97uqAtt/1342-epicaquiferdata-tweaks-2)

**Comment by rfb** [comment]
@stephenhillier @Sybrand 

Can you take a look at this? My greatest concern here is I added lodash and it turned into a rather large `package-lock.json` change. I _think_ the version of npm in the docker container is different then the npm version you both have installed - so it's calculated the dependencies differently. 

```
root@c1f514daac29:/# node -v
v8.12.0
root@c1f514daac29:/# npm -v
6.4.1
```

**Comment by Sybrand** [comment]
> @stephenhillier @Sybrand
> 
> Can you take a look at this? My greatest concern here is I added lodash and it turned into a rather large `package-lock.json` change. I _think_ the version of npm in the docker container is different then the npm version you both have installed - so it's calculated the dependencies differently.
> 
> ```
> root@c1f514daac29:/# node -v
> v8.12.0
> root@c1f514daac29:/# npm -v
> 6.4.1
> ```

a.f.a.i.k. the version of npm throughout should be 5.6.0 @DerekRoberts @stephenhillier can we get docker to have the same npm as our environments in openshift?

```

**Comment by rfb** [comment]
npm 5.6.0 looks like nodes version 9.4.0 to 10.2.1 

https://nodejs.org/en/download/releases/

**Comment by rfb** [comment]
I'm rebuilding with the node:10.12 docker container .. I'll see if it fixes the lock

**Comment by Sybrand** [comment]
@rfb correct version of node to use is v8.9.4

**Comment by rfb** [comment]
it looks like docker/node doesn't offer 8.9, only 8.12 - maybe docker/node only offers the latest supported/stable version? All the node versions in docker/node use npm 6.4.x

**Comment by rfb** [comment]
using node:8.9.4 - thanks for discovering that image @stephenhillier

**Pull request closed without merging**
