### PR TITLE
[1149] Script Updates

### PR DESCRIPTION
**Pull request by DerekRoberts**

### CODE REVIEW

**Comment by DerekRoberts** [comment]
[EPIC#Pipeline | Mid post-deploy.sh failing  |2| !!](https://trello.com/c/3njCfbyS/1151-epicpipeline-mid-post-deploysh-failing-2)

**Comment by garywong-bc** [comment]
@DerekRoberts  no changes needed. it works as -is:
(.venv) garywong@NCM050128:scripts$ ./post-deploy.sh 
+ IFS='
	'
+ echo 'Post-Deploy: SQL imports'
Post-Deploy: SQL imports
+ cd /Users/garywong/proj/gwells/src/database/scripts/wellsearch/
+ psql -X --set ON_ERROR_STOP=on -h localhost -d gwells -U gwells -f post-deploy.sql
DROP INDEX
CREATE INDEX
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
+ psql -X --set ON_ERROR_STOP=on -h localhost -d gwells -U gwells -f wells_replication_stored_functions.sql
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
+ echo 'Post-Deploy: Python tasks'
Post-Deploy: Python tasks
+ cd /Users/garywong/proj/gwells/src/
+ python manage.py post-deploy
REQUIRE_ENV_VARIABLES is set to False
Test user already exists (username: "testuser").
Group gwells_administrator exists
Group registries_statutory_authority exists
Group registries_adjudicator exists
Group registries_staff_viewer exists
Admin user already exists (username: "admin").
+ echo 'Post-Deploy: completed successfully'
Post-Deploy: completed successfully

**Comment by garywong-bc** [comment]
With error-checking on:
(.venv) garywong@NCM050128:scripts$ ./post-deploy.sh 
+ IFS='
	'
+ echo 'Post-Deploy: SQL imports'
Post-Deploy: SQL imports
+ cd /Users/garywong/proj/gwells/src/database/scripts/wellsearch/
+ set +x
+ SQL_FILES=("post-deploy.sql" "wells_replication_stored_functions.sql")
+ for s in '${SQL_FILES[@]}'
+ psql -X --set ON_ERROR_STOP=on -h localhost -d gwells -U gwells -f post-deploy.sql
DROP INDEX
CREATE INDEX
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
+ for s in '${SQL_FILES[@]}'
+ psql -X --set ON_ERROR_STOP=on -h localhost -d gwells -U gwells -f wells_replication_stored_functions.sql
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
+ echo 'Post-Deploy: Python tasks'
Post-Deploy: Python tasks
+ cd /Users/garywong/proj/gwells/src/
+ python manage.py post-deploy
REQUIRE_ENV_VARIABLES is set to False
Test user already exists (username: "testuser").
Group gwells_administrator exists
Group registries_statutory_authority exists
Group registries_adjudicator exists
Group registries_staff_viewer exists
Admin user already exists (username: "admin").
+ echo 'Post-Deploy: completed successfully'
Post-Deploy: completed successfully

**Comment by DerekRoberts** [comment]
[EPIC#Pipeline | Many Stuck PR Jobs Slowing Jenkins |2| !!](https://trello.com/c/pBlDm4RC/1164-epicpipeline-many-stuck-pr-jobs-slowing-jenkins-2)

**Comment by DerekRoberts** [comment]
[EPIC#Pipeline | Jenkins Stopping Builds at 10 Pods |2| !!](https://trello.com/c/ELYH2jqm/1168-epicpipeline-jenkins-stopping-builds-at-10-pods-2)

**Pull request merged**
